# Problem Statement 1:
Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde

In [1]:
import numpy as np

def vandermonde_matrix(data, N = None, increasing = False):
    if N==None:
        N = len(data)
    if increasing:
        result = [[pow(elmnt, power) for power in range(0, N)] for elmnt in data]
        print(np.asanyarray(result))
    else:
        result = [[pow(elmnt, power) for power in range(N-1, -1, -1) ] for elmnt in data]
        print(np.asanyarray(result))

In [2]:
data = [2,4,6,8,10]        
vandermonde_matrix(data,5,increasing = False)

[[   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]]


In [3]:
data = [2,4,6,8,10]        
vandermonde_matrix(data,6,increasing = True)

[[     1      2      4      8     16     32]
 [     1      4     16     64    256   1024]
 [     1      6     36    216   1296   7776]
 [     1      8     64    512   4096  32768]
 [     1     10    100   1000  10000 100000]]


# 2>> Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values

# Question:
Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
def mov_avg(data, N):
    cumsum, moving_avgs = [0], []
    
    for i, x in enumerate(data, 1):
        cumsum.append(cumsum[i-1] + x)
        if i>=N:
            moving_avg = round(((cumsum[i] - cumsum[i-N])/N),2)
            moving_avgs.append(moving_avg)
    
    print("Moving average: ", moving_avgs)
    print("Length of the list l-N+1: ", len(moving_avgs))

In [5]:
data=[10,20,30,40,50,60,70,80,90,100,110,120]
mov_avg(data,4)

Moving average:  [25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0, 95.0, 105.0]
Length of the list l-N+1:  9
